# Node.js CI workflow

# react runs unique tests if the CI environment variable is set
# build: base href is set in package.json at homepage

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run lint
      run: yarn run lint
    - name: Run tests
      run: yarn run test-ci
    - name: Build
      run: yarn run build-ci
    - name: Push to gh-pages (if master branch)
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.email github-actions@github.com
        git config user.name github-actions
        git checkout gh-pages
        rm -Rf ./demo/trunk/*
        cp -Rf ./build/* ./demo/trunk
        git add ./demo/trunk/*
        git diff-index --quiet HEAD || git commit -m "CI run ${{ github.run_number }} update gh-pages"
        git push -fq origin gh-pages
